### ISSUE TITLE
Class "Faker\Factory" not found  

### ISSUE THREAD

**Issue by asakous** [davymaish/harambee#3]
after run php artisan migrate --seed
I got this error. it seems fakerphp/faker is missing.

![螢幕擷取畫面 2023-09-14 094736](https://github.com/davymaish/harambee/assets/6611523/ccff3d5c-f852-470f-964a-3db0ffe452a0)

**Comment by davymaish** [comment]
The error above is thrown by the UserSeeder. I have tested the seeders on my end and are working correctly. If you have modified the UserSeeder, then it means the error is thrown by the changes you made. Check and make sure that the UsersSeeder and UserFactory(inside database/factories) are exactly as they are in the repo.  If you want to keep your changes, share the code in your UserSeeder.php and I might help you debug the error

**Comment by cliche23** [comment]
> after run php artisan migrate --seed I got this error. it seems fakerphp/faker is missing.
> 
> ![螢幕擷取畫面 2023-09-14 094736](https://user-images.githubusercontent.com/6611523/267828409-ccff3d5c-f852-470f-964a-3db0ffe452a0.png)

You should run composer install without `--no-dev` flag since fakerphp is installed as a dev dependency. The readme file should mention this.
