### ISSUE TITLE
nodeJs version problem

### ISSUE THREAD

**Issue by asakous** [davymaish/harambee#4]
I use Ubuntu 20.04 as my dev env . the default nodeJs version is 10.xx .
because of nodeJs version . I wasn't able to run npm run dev. I got some errors.
so I think you should point out the minimum version of nodeJs is required.
I tested node version 18 is ok. 

another problem is [npm i] command is  required after [setup database tables: php artisan migrate --seed]

**Comment by davymaish** [comment]
I made updates some few days ago and now compiling your assets (running npm) isn't a requirement to run the application. If you have made some changes in the assets folder,  you can ran npm normally as you would in a new Laravel 10 project. That means you can safely use the latest version of npm without bumping into any error.
